### ISSUE TITLE
iOS 64-bit Support problem

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/VideoCapturePlus-PhoneGap-Plugin#25]
according to this
http://phonegap.com/blog/2015/01/20/ios-64bit-support/
this plugin will install fail by PGB (build.phonegap.com) for now

**Comment by oliverholmberg** [comment]
Hmmm.... Using this plugin on in a PG app (Version 3.6.3) built with Phonegap Build.  In that PG version, the ARM64 binary should be being used when I run on iPhone6/ios 8.

It seems to work just fine. @bau720123 have you tested?

**Comment by bau720123** [comment]
hi @oliverholmberg 
I tested
if I use your plugin in PGB 3.6.3，it will build fail that only in iOS
on the contrary
it will build success

**Comment by bau720123** [comment]
hi @oliverholmberg 
problem solved
thanks
