### ISSUE TITLE
Plugin doesn't load with PhoneGap Build and iOS.

### ISSUE THREAD

**Issue by hallis2** [EddyVerbruggen/VideoCapturePlus-PhoneGap-Plugin#39]
I've tried to initiate this plugin for 3 hours now but with no success. I use PhoneGap Desktop and an iPhone 5 with iOS 9 installed.

I put this in my config.xml file
```
<gap:plugin name="nl.x-services.plugins.videocaptureplus" />
```

I have commented out both `org.apache.cordova.media-capture` and `org.apache.cordova.camera` (just in case) if this had anything to do with it.

When i try to execute it I do like this but the only thing that happens is that console says "before".
```
console.log("BEFORE");
window.plugins.videocaptureplus.captureVideo(function() {
	alert("YES");
}, function(error) {
	alert(error.code + ': ' + error.message);
}, {
	limit: 1,
	duration: 15,
	highquality: true,
	frontcamera: true
});
console.log("AFTER");
```

During my debugging I executed this `console.log(window.plugins.videocaptureplus)` and it resulted in `null` which got me to believe the plugin isn't loaded in the first place.

Am I doing something wrong here?

**Comment by EddyVerbruggen** [comment]
Do you wait for deviceready to fire before this code executes?

**Comment by hallis2** [comment]
Yes, the function are executed by a click event that I assign with that function
```
onDeviceReady: function() {
	document.getElementById('recordBtn').addEventListener("click", function() {
		var video = new VideoRecordning();
		video.initialize();
	});
},
```

And `VideoRecordning()` looks like this:
```
function VideoRecordning() {
	this.initialize = function(){
		
	console.log("BEFORE");
	window.plugins.videocaptureplus.captureVideo(function() {
		alert("YES");
	}, function(error) {
		alert(error.code + ': ' + error.message);
	}, {
		limit: 1,
		duration: 15,
		highquality: true,
		frontcamera: true
	});
	console.log("AFTER");
	}
}
```

**Comment by hallis2** [comment]
I am completely new to PhoneGap and understand now that when using the iOS PhoneGap Developer app it does not include plugins like thees, only the PhoneGap native function.

**Comment by EddyVerbruggen** [comment]
Ah, good point, thanks for sharing!
