### ISSUE TITLE
Cordova iOS-4.0.1 Problem

### ISSUE THREAD

**Issue by elysiopires** [EddyVerbruggen/VideoCapturePlus-PhoneGap-Plugin#40]
Hello Everyone,

I having a problem with videocaptureplus plugin over latest version of cordova@4.0.1 IOS.

When I build my application I receive the erros:

/Users/elysiopires/Documents/Project Products/Softwares/Mobile/PROJECT/platforms/ios/PROJECT/Plugins/nl.x-services.plugins.videocaptureplus/VideoCapturePlus.m:49:38: No visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'

/Users/elysiopires/Documents/Cartomobi Products/Softwares/Mobile/PROJECT/platforms/ios/PROJECT/Plugins/nl.x-services.plugins.videocaptureplus/VideoCapturePlus.m:103:13: Implicit declaration of function 'CDV_IsIPad' is invalid in C99

Could anyone help me please?

Thx

![problemcameraplus](https://cloud.githubusercontent.com/assets/4189312/12390233/5882227a-bdc5-11e5-8c5c-79ccccc7945d.png)

**Comment by EddyVerbruggen** [comment]
Use cordova-ios-3 for now, until someone fixes it.

**Comment by eweap** [comment]
Fixed in #41
