### ISSUE TITLE
portraitOverlay and landscapeOverlay image not display - Android

### ISSUE THREAD

**Issue by subhash8108** [EddyVerbruggen/VideoCapturePlus-PhoneGap-Plugin#51]
Hello,

I have used your plugin, IOS perfect work portraitOverlay and landscapeOverlay image orientation but android is not working..

Is it possible to work on android application?

Cordova version - 6.5.0
![ipmsgclip_s_1501071152_0](https://user-images.githubusercontent.com/542535/28620300-f399e328-7229-11e7-96fd-12406d14c854.png)

Thanks
Subhash Patel

**Comment by EddyVerbruggen** [comment]
Correct, to quote the readme: "A custom overlay (currently iOS only)."
